export type RootStackParamList = {
    Home: undefined;
    ModularPlayground: undefined;
    Toolbox: undefined;
    UlamSpiral: undefined;
    Sieve: undefined;
    EuclideanVisualizer: undefined;
    ModularTable: undefined;
    Collatz: undefined;
    Factorization: undefined;
    LCM: undefined;
    PascalTriangle: undefined;
    Fibonacci: undefined;
    Totient: undefined;
    Divisors: undefined;
    PrimitiveRoots: undefined;
    ContinuedFraction: undefined;
    ModularInverse: undefined;
    ModularExponentiation: undefined;
};
